kubectl delete rc nginx-ingress-rc
kubectl delete rc mysql-rc
kubectl delete rc web-frontend-rc
kubectl delete --all pods
kubectl delete svc mysql
kubectl delete svc web-frontend-svc
kubectl delete svc nginx-ingress-rc
kubectl delete ingress web-ingress
kubectl delete secret web-secret
