apiVersion: v1
kind: ReplicationController
metadata:
  name: web-frontend-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-frontend-rc
    spec:
      containers:
        - image: redis
          name: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
        - image: brunoterkaly/py-red
          name: python
          env:
            - name: REDIS_HOST
              value: localhost
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
